### PR TITLE
Fix and test case for supporting members with dollar signs

### LINKED ISSUE #2177: Opening files with $ sign in name
We can't open files/members any more when name of it has a $ sign in it for example ren$sign.cblle. This is not the case when I went back to 2.9.0. 
After that I tried every version and did not work any more. What did change? And I feel like depending on versions readonly and position attributes don't work the way expected.
Help appreciated.
Thank you.

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

Fixes #2177 by not escaping at the right time.

* A new test case with members with dollar signs in the name has been added
* Renamed `sanitise` to `noEscape` to make more sense based on the existing code logic

### How to test this PR

Examples:

1. Run the test cases
2. Try creating and editing a member with a dollar sign

### Checklist

* [x] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by worksofliam** [comment]
It seems like there might be some contention between where the encoding actually happens. I am passing `true` to `qualifyPath` so it doesn't escape:

https://github.com/codefori/vscode-ibmi/blob/fix/dollars_in_names/src/api/IBMiContent.ts#L152

As I am expecting it to be escaped in the `runCommand` function: https://github.com/codefori/vscode-ibmi/blob/fix/dollars_in_names/src/api/CompileTools.ts#L681

File: src/api/IBMiContent.ts [hunk 1]
```diff
@@ -261,7 +261,6 @@ export default class IBMiContent {
               //The member may be located on SYSBAS
               if (asp) {
                 path = Tools.qualifyPath(library, sourceFile, member);
-                retry = true;
```
Comment (sebjulliand) [inline src/api/IBMiContent.ts:264]: Why have you removed `retry = true` here?

**Review by sebjulliand — CHANGES_REQUESTED** [review]
Code looks good to me. Replacing `sanitize` with `noEscape` is great...makes a lot more sense!
See my remark about that line being removed though.

**Comment by worksofliam** [comment]
@sebjulliand Not sure why I did that. Re-requested your review.

**Review by sebjulliand — APPROVED** [review]
Approved and good to go!
