### PR TITLE
Fix rename/move on IFS directories

### LINKED ISSUE #2103: `Rename/Move...` action fails on IFS directories
The `Rename/Move...` action fails on directories in the IFS Browser.

image

|Context|Version|
|-|-|
|Code for IBM i version|2.10.7|
|Visual Studio Code version|1.90.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Debug (ibmidebug): 1.0.0
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.10.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WCA@IBM (wca-at-ibm): 6.3.0
WSL (remote-wsl): 0.88.2
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID Origin|65535|
|Runtime CCSID|273|
|Default CCSID|273|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=AURORADEU
CURLIB=AURORADEU
HOME=/home/SANJULA
HOST=p8adt05.rch.stglabs.ibm.com
LIBLS=QTEMP QGPL TESTTOOLS
LOGIN=sanjula
LOGNAME=sanjula
MAIL=/var/spool/mail/sanjula
OLDPWD=/home/SANJULA
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin:
PWD=/home/SANJULA
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=9.61.64.31 18553 22
SSH_CONNECTION=9.61.64.31 18553 9.5.12.241 22
TZ=<UTC>0
USER=sanjula
USERNAME=sanjula
WORKDIR=/home/SANJULA
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.",
    "cwd": "/home/SANJULA"
  }
]
```
</details>

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
### Changes

Fixes #2103

### How to test this PR

Examples:

1. Run the test cases
2. Expand view A and right click on the node
3. Run 'Execute Thing' from the command palette

### Checklist

* [x] have tested my change

### CODE REVIEW

File: src/views/ifsBrowser.ts [hunk 1]
```diff
@@ -616,16 +616,19 @@ export function initializeIFSBrowser(context: vscode.ExtensionContext) {
...
-        vscode.window.showErrorMessage(t("ifsBrowser.moveIFS.errorMessage", t(String(node.contextValue)), t("file.path.not.parsed")));
-        return;
-      }
-      // Check if the streamfile is currently open in an editor tab
-      const oldFileTabs = Tools.findUriTabs(node.resourceUri);
-      if (oldFileTabs.find(tab => tab.isDirty)) {
-        vscode.window.showErrorMessage(t("ifsBrowser.moveIFS.errorMessage", t(String(node.contextValue)), t("file.unsaved.changes")));
-        return;
+      const oldFileTabs: vscode.Tab[] = [];
+      if (node.contextValue?.startsWith(`streamfile`)) {
```
Comment (sebjulliand) [inline src/views/ifsBrowser.ts:620]: It may be safer to check `file.type` here; if the `contextValue` changes in the future, this won't break.
```suggestion
      if (node.file.type === "streamfile") {
```

**Review by sebjulliand — CHANGES_REQUESTED** [review]
Good catch @SanjulaGanepola!
I just have one suggestion. Otherwise it looks good!

**Review by sebjulliand — CHANGES_REQUESTED** [review]
Code looks good and it works fine, thank you!
Now, to keep a good UX, could you add a check similar to the one done when renaming a file, to ensure every tab opened is saved before it gets renamed? When a folder gets renamed, checking if every tab opened is not dirty when its document path starts with `${node.file.path}/` (adding the / at the end to avoid false positives) should do the trick.
What do you think?

**Comment by SanjulaGanepola** [comment]
Good idea to keep the behavior consistent between stream files and directories. Updated the PR.

**Comment by chrjorgensen** [comment]
@sebjulliand Danish translation is in...

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@SanjulaGanepola I found an (old?) error - to reproduce:
1. Open a file in a directory (do not change it)
2. Rename the directory containing the file
3. The new directory is opened as a file, causing an error message:

billede

**Comment by chrjorgensen** [comment]
@NicolasSchindler You changed the Danish translation file instead of the German translation file in commit [3fd6f90](https://github.com/codefori/vscode-ibmi/pull/2104/commits/3fd6f903f0b047f8ec1503a7117f805260e87f70) - could you please fix this? 😉

**Comment by sebjulliand** [comment]
> @NicolasSchindler You changed the Danish translation file instead of the German translation file in commit [3fd6f90](https://github.com/codefori/vscode-ibmi/pull/2104/commits/3fd6f903f0b047f8ec1503a7117f805260e87f70) - could you please fix this? 😉

This one's on me since @NicolasSchindler couldn't commit directly on this branch? I'll fix it!

**Comment by SanjulaGanepola** [comment]
> 3. The new directory is opened as a file, causing an error message:

@chrjorgensen Thanks for catching that issue. Fixed it -> [2ec6e40](https://github.com/codefori/vscode-ibmi/pull/2104/commits/2ec6e40514c47ab8d50651ce798fd80aa1198268)

FYI, also found another issue where the `mv` command would fail but no error was shown if for example you tried to move a file to a directory that does not exist. Fixed this as well -> [19552a5](https://github.com/codefori/vscode-ibmi/pull/2104/commits/19552a5714b7d0bcf0a6ad5c43a3579faea608ef)

**Comment by worksofliam** [comment]
@SanjulaGanepola Please update the 'How to test' in the PR.

**Comment by worksofliam** [comment]
@SanjulaGanepola 'Move/Rename...' works as expected. Do let me know if there is more than needs testing.

**Review by chrjorgensen — APPROVED** [review]
@SanjulaGanepola Looking great, working as expected and fixes the errors. 👍

**Comment by SanjulaGanepola** [comment]
> @SanjulaGanepola 'Move/Rename...' works as expected. Do let me know if there is more than needs testing.

Sorry for the late reply. I see this was already merged, but yes only "Move/Rename" needed to be tested on directories
