### PR TITLE
Fix custom variable editor

### LINKED ISSUE #2590: Editing custom variables opens new variable panel
I don't know when this started but it was not recently.  Whenever, I attempt to modify a custom variable, I only get the new variable panel.  So this leaves me to edit settings directly.

Image

Image

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.15.3|
|Visual Studio Code version|1.95.3|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
All Autocomplete (All-Autocomplete): 0.0.26
CL (vscode-clle): 1.1.7
Code Spell Checker (code-spell-checker): 4.0.40
Code for IBM i User Spooled Files (vscode-ibmi-userspooledfiles): 0.2.0
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Data Preview (vscode-data-preview): 2.3.0
Db2 for IBM i (vscode-db2i): 1.9.4
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.24.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
Hawkeye Pathfinder (vscode-ibmi-hawkeye): 0.1.2
IBM i Renderer (vscode-displayfile): 0.1.3
JSON Language Features (json-language-features): 1.0.0
JSON to CSV (json2csv): 1.0.0
Markdown Language Features (markdown-language-features): 1.0.0
Markdown Math (markdown-math): 1.0.0
Markdown Preview Enhanced (markdown-preview-enhanced): 0.8.18
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Partial Diff (partial-diff): 1.4.3
Query JSON - lite (query-json-lite): 0.5.1
REST Client (rest-client): 0.25.1
RPGLE (vscode-rpgle): 0.28.9
RPGLE Free (vscode-rpgfree): 0.0.34
Rainbow CSV (rainbow-csv): 3.18.0
Remove empty lines (remove-empty-lines): 1.0.1
TODO Highlight (vscode-todo-highlight): 1.0.5
Text Marker (Highlighter) (text-marker): 1.11.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
scratch-code (scratch-code): 0.1.8
undefined (indent-rainbow): 8.3.1
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|5|
|CCSID Origin|37|
|Runtime CCSID|37|
|Default CCSID|37|
|SSHD CCSID|?|
|cqsh|true|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|/QOpenSys/QIBM/ProdData/JavaVM/jdk80|/QOpenSys/QIBM/ProdData/JavaVM/jdk11|
|-|-|-|-|-|-|
|bash|attr|QZDFMDB2.PGM|startDebugService.sh|64bit|64bit|
|find|iconv|||||
|git|setccsid|||||
|grep|uname|||||
|ls||||||
|md5sum||||||
|sort||||||
|stat||||||
|tar||||||
|tn5250||||||
</details>

<details>
<summary>Shell env</summary>
</details>
<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Fixes #2590 

- Fixed variable edition (variable id was not retrieved correctly
- Added types for Custom Variables pages (list and editor)
- Removes any `&` in variable name
- Turn static class into namespace and refactored the code a bit

### How to test this PR
1. Open the custom variables list
2. Create a new variable: it must appear in the list
  - Try to start the name with `&` : it must be removed
4. Edit the variable: save and the changes should appear in the list
5. Delete the variable: it must be removed from the list

### Checklist
* [x] have tested my change

### CODE REVIEW

File: src/webviews/variables/index.ts [hunk 1]
```diff
@@ -1,103 +1,91 @@
...
-      vscode.commands.registerCommand(`code-for-ibmi.showVariableMaintenance`, async () => {
-        this.MainMenu();
-      })
+      vscode.commands.registerCommand(`code-for-ibmi.showVariableMaintenance`, openVariablesList)
     )
   }
 
-  static async MainMenu() {
+  async function openVariablesList() {
     const config = instance.getConfig();
```
Comment (worksofliam) [inline src/webviews/variables/index.ts:26]: Can this please use `connection.getConfig()`?

**Review by worksofliam — CHANGES_REQUESTED** [review]

**Comment by worksofliam** [comment]
Works good, but perhaps a little spacing between the text and the items here?

image

File: src/webviews/variables/index.ts (hunk 1 above)
Comment (sebjulliand) [reply src/webviews/variables/index.ts:26]: Sure! With the cleanup PR now merged I thought this one would have to be merged.

**Comment by sebjulliand** [comment]
Cleanup done, spacing added (visible in actions management view too). All yours @worksofliam !

File: src/webviews/variables/index.ts (hunk 1 above)
Comment (worksofliam) [reply src/webviews/variables/index.ts]: Seems I missed a spot 😅

Comment (sebjulliand) [reply src/webviews/variables/index.ts]: Got you covered 😁

**Review by worksofliam — APPROVED** [review]
@sebjulliand Tested again and it's looking good.

Thanks!
